CREATE TABLE fact_customers (
    id INT PRIMARY KEY,
    year_birth INT,
    education VARCHAR(30),
    marital_status VARCHAR(20),
    income DECIMAL,
    kidhome INT,
    teenhome INT,
    dt_customer DATE,
    recency INT,
    mntwines DECIMAL,
    mntfruits DECIMAL,
    mntmeatproducts DECIMAL,
    mntfishproducts DECIMAL,
    mntsweetproducts DECIMAL,
    mntgoldprods DECIMAL,
    numdealspurchases INT,
    numwebpurchases INT,
    numcatalogpurchases INT,
    numstorepurchases INT,
    numwebvisitsmonth INT,
    acceptedcmp3 INT,
    acceptedcmp4 INT,
    acceptedcmp5 INT,
    acceptedcmp1 INT,
    acceptedcmp2 INT,
    complain INT,
    z_costcontact INT,
    z_revenue INT,
    response INT,
    age INT,
    customer_tenure_days INT,
    total_spend DECIMAL,
    total_campaigns_accepted INT,
    family_size INT,
    income_bracket VARCHAR(20),
    age_group VARCHAR(10)
);